import { Navbar } from "../components/Navbar"
import { Footer } from "../components/Footer"
import { usePageViewTracker } from "../hooks/usePageViewTracker"

export function Terms() {
  usePageViewTracker("/terms")

  return (
    <>
      <Navbar />

      <section style={{ textAlign: "center", maxWidth: 1250, margin: "0 auto", padding: "40px 30px", backgroundColor: "#0B0A2B" }}>
        <h1 style={{ fontSize: 56, fontWeight: "bold", color: "white", fontFamily: "'Glacial Indifference', sans-serif" }}>Terms of Use</h1>
      </section>

      <div style={{ position: "relative", width: "100%", height: 10, backgroundColor: "white" }}>
        <div style={{ position: "absolute", top: -50, left: 0, width: "100%", height: 100, backgroundColor: "#0B0A2B", borderBottomLeftRadius: 50, borderBottomRightRadius: 50 }} />
      </div>

      <br /><br /><br /><br /><br />

      <div style={{ backgroundColor: "white", display: "flex", justifyContent: "center" }}>
        <section style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 18, lineHeight: 1.6, color: "#333", backgroundColor: "white", padding: "0 20px", maxWidth: 1250 }}>
          <h1 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>1. Acceptance of the Terms of Use</h1>
          <p>These terms of use are entered into by and between You and Future Forward ("Company," "we," or "us"). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, "Terms of Use"), govern your access to and use of www.ffcareers.app (the "Website"), whether as a guest or a registered user.</p>
          <p>Please read the Terms of Use carefully before you start to use the Website. By using the Website, you accept and agree to be bound and abide by these Terms of Use and our <a href="/privacy" style={{ color: "#9b2429" }}>Privacy Policy</a>. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the Website.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>1A. Disclaimer Regarding Career Guidance</h2>
          <p>Future Forward provides career exploration tools and resources for informational and entertainment purposes only. The information, insights, or suggestions generated by the app do not constitute professional career, psychological, or educational advice and should not be treated as such.<br />We make no guarantees as to the accuracy, completeness, or suitability of the results provided. All results and insights are provided "as is," without any warranties, express or implied. Users are encouraged to seek guidance from qualified professionals before making any career decisions.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>1A. Disclaimer Regarding Privacy and Artificial Intelligence Providers</h2>
          <p>Use of AI Services: By using the App, you acknowledge and agree that certain features may rely on third-party artificial intelligence services (such as ChatGPT by OpenAI) to function. These services may process information you provide, including inputted task names and other user-generated content, as further outlined in our <a href="/privacy" style={{ color: "#9b2429" }}>Privacy Policy</a>.</p>
          <p>You are responsible for ensuring that you do not submit any confidential, sensitive, or legally protected information through AI-assisted features. We do not control how third-party AI providers collect, use, store, or disclose the information they process. Accordingly, we disclaim all liability arising from or related to the use of such third-party AI services.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>1B. Changes to the Terms of Use</h2>
          <p>We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>2. Children Under the Age of 13</h2>
          <p>Our Website is not intended for children under 13 years of age. No one under age 13 may provide any information to or on the Website. We do not knowingly collect personal information from children under 13. If you are under 13, do not use or provide any information on this Website or through any of its features. If we learn we have collected or received personal information from a child under 13 without verification of parental consent, we will delete that information. Contact us at <a href="mailto:contact@futureforward.info" style={{ color: "#9b2429" }}>contact@futureforward.info</a>.<br />California residents under 16 years of age may have additional rights regarding the collection and sale of their personal information.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>10. Contact Information</h2>
          <p>To ask questions or comment about this privacy policy and our privacy practices, contact us at: <a href="mailto:contact@futureforward.info" style={{ color: "#9b2429" }}>contact@futureforward.info</a>.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>17. Disclaimer of Warranties</h2>
          <p>You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Website will be free of viruses or other destructive code. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE.<br /><br />YOUR USE OF THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>24. Entire Agreement</h2>
          <p>The Terms of Use, and our Privacy Policy, constitute the sole and entire agreement between you and the Company regarding the Website and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Website.</p>

          <h2 style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 24, marginBottom: 15 }}>25. Your Comments and Concerns</h2>
          <p>All feedback, comments, requests for technical support, and other communications relating to the Website should be directed to: contact@futureforward.info.</p>
        </section>
      </div>

      <Footer />
    </>
  )
}
